services:
  - type: web
    name: recipe-explorer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SPOONACULAR_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false